name: Deploy Python Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    # steps:
    # - uses: actions/checkout@master
    # - name: Deploy code to Lambda
    #   uses: mariamrf/py-lambda-action@v1.0.0
    #   with:
    #     # lambda_layer_arn: 'arn:aws:lambda:us-east-1:123456789012:layer:lamda-check'
    #     lambda_function_name: 'lamda_check'
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     AWS_DEFAULT_REGION: 'us-east-1'
    steps:
      - name: checkout source code
        uses: actions/checkout@v1
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: 'us-east-1'
          function_name: lambda_check
          source: function.py